#CS2211a 2020
#Assignment 05
#Mir Mubasher
#251077816
#mmubash3
#30th Nov 2020

$(CC) = gcc
myParagraph:
	$(CC) main.c find_word.c helper_function.c setting_struct.c delete_function.c print_functions.c -o myParagraph
make clean:
	rm myParagraph
